# Generated by Django 4.1.7 on 2023-02-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Ticker', models.CharField(max_length=5)),
                ('Picture', models.CharField(max_length=100, null=True)),
                ('Number_of_shares', models.IntegerField()),
                ('Country', models.CharField(max_length=30)),
                ('Currency', models.CharField(default='dollar', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Administrator', models.BooleanField(default=False)),
                ('Manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('Time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('Price', models.FloatField()),
                ('Change_percent', models.FloatField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursach_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_shares', models.IntegerField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursach_app.company')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursach_app.user')),
            ],
        ),
    ]
