# Generated by Django 4.1.7 on 2023-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AddField(
            model_name='operations',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
