# Generated by Django 4.1.7 on 2023-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0002_rename_company_id_operations_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'get_latest_by': ['time']},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
