# Generated by Django 4.1.7 on 2023-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0002_alter_company_options_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name_plural': 'Operations'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
