# Generated by Django 4.1.7 on 2023-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0003_alter_stocks_options_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='INN',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
