# Generated by Django 4.1.7 on 2023-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0003_alter_operations_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
