# Generated by Django 4.1.7 on 2023-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0005_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
