# Generated by Django 4.1.7 on 2023-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0006_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=False),
        ),
    ]
