# Generated by Django 4.1.7 on 2023-04-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursach_app', '0007_stocks_id_alter_stocks_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='INN',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
